### ISSUE TITLE
headphone static noise

### ISSUE THREAD

**Issue by hlla** [lienkheict/Dell-M4800-Hackintosh#1]
Thank you for your  share, I successfully  installed Catalina on my Dell m4800.
I find three problems:
1. static noise from the headphones 
2. some USB ports on the Dell Dock E-Port Plus PR02X Advanced Port Replicator not work
3. PR02X dual display port for 5K display only 4K

**Comment by lienkheict** [comment]
1. Please check other code audio
2. I don't have Dell Dock?
3. I don't have a 4K or 5K display to try
Sorry!

**Comment by hlla** [comment]
Thank you again for the great job.

**Comment by hlla** [comment]
the headphones static noise can be solved like [this](https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-t440p-opencore-0-5-9.299277/) with layoutid 28
![audio_setting](https://user-images.githubusercontent.com/7305059/102893139-01c1d800-449c-11eb-8abf-25cac8aebe4d.jpg)

**Comment by lienkheict** [comment]
Thank you for sharing!
Code 28 is not right for me but will work for everyone!
